version: '3.8'
services:
  quasar:
    container_name: app-template  #TODO: Set your desired container name here
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '9000:9000'
    volumes:
      - ./app:/app
    command: /bin/sh -c "npm install && quasar dev"
